#!/usr/bin/env bash

# 1. Install all dependencies in Ubuntu 20.04

set -eoux pipefail

sudo apt update
sudo apt install -y \
    autoconf \
    automake \
    bsd-mailx \
    dbus-x11 \
    debhelper \
    dpkg-dev \
    gcc \
    gcc-10 \
    gvfs \
    imagemagick \
    language-pack-en-base \
    libacl1-dev \
    libasound2 \
    libasound2-dev \
    libaspell15 \
    libasyncns0 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libbrotli1 \
    libcairo-gobject2 \
    libcairo2 \
    libcanberra-gtk3-0 \
    libcanberra-gtk3-module \
    libcanberra0 \
    libcroco3 \
    libdatrie1 \
    libdb5.3 \
    libdbus-1-dev \
    libdrm2 \
    libegl1 \
    libenchant1c2a \
    libepoxy0 \
    libflac8 \
    libfontconfig1 \
    libfreetype6 \
    libgbm1 \
    libgccjit-10-dev \
    libgccjit0 \
    libgdk-pixbuf2.0-0 \
    libgif-dev \
    libgif-dev libgnutls28-dev libgpm-dev \
    libgif7 \
    libgl1 \
    libglvnd0 \
    libglx0 \
    libgnutls28-dev \
    libgpm2 \
    libgraphite2-3 \
    libgstreamer-gl1.0-0 \
    libgstreamer-plugins-base1.0-0 \
    libgstreamer1.0-0 \
    libgtk-3-0 \
    libgtk-3-dev \
    libgudev-1.0-0 \
    libharfbuzz-bin \
    libharfbuzz-dev \
    libharfbuzz-icu0 \
    libharfbuzz0b \
    libhyphen0 \
    libice6 \
    libicu66 \
    libjansson-dev \
    libjansson4 \
    libjavascriptcoregtk-4.0-18 \
    libjbig0 \
    libjpeg-dev \
    libjpeg-turbo8 \
    liblcms2-2 \
    liblcms2-dev \
    liblockfile-dev \
    liblockfile1 \
    libltdl7 \
    libm17n-0 \
    libm17n-dev \
    libmagickwand-dev \
    libncurses5-dev \
    libnotify4 \
    libnss-mdns \
    libnss-myhostname \
    libnss-systemd \
    libogg0 \
    liborc-0.4-0 \
    liboss4-salsa2 \
    libotf-dev \
    libotf0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpangoft2-1.0-0 \
    libpixman-1-0 \
    libpng-dev \
    libpng16-16 \
    libpulse0 \
    librsvg2-2 \
    librsvg2-dev \
    libsasl2-2 \
    libsecret-1-0 \
    libselinux1-dev \
    libsm6 \
    libsndfile1 \
    libsoup2.4-1 \
    libssl1.1 \
    libstdc++6 \
    libsystemd-dev \
    libtdb1 \
    libthai0 \
    libtiff-dev \
    libtiff5 \
    libtiff5-dev \
    libvorbis0a \
    libvorbisenc2 \
    libvorbisfile3 \
    libwayland-client0 \
    libwayland-cursor0 \
    libwayland-egl1 \
    libwayland-server0 \
    libwebp6 \
    libwebpdemux2 \
    libwoff1 \
    libx11-6 \
    libx11-dev \
    libx11-xcb1 \
    libxau6 \
    libxcb-render0 \
    libxcb-shm0 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxdmcp6 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxinerama1 \
    libxkbcommon0 \
    libxml2 \
    libxml2-dev \
    libxpm-dev \
    libxpm4 \
    libxrandr2 \
    libxrender1 \
    libxslt1.1 \
    libyajl2 \
    make \
    procps \
    quilt \
    sharutils \
    texinfo \
    xaw3dg-dev \
    zlib1g-dev \
